export const LABEL = "Actions";
export const OPTIONS = [
  "attacking",
  "jump attack",
  "running attack",
  "critical hit",
  "two-handing",
  "blocking",
  "parrying",
  "guard counter",
  "sorcery",
  "incantation",
  "skill",
  "summoning",
  "throwing",
  "healing",
  "running",
  "rolling",
  "backstepping",
  "jumping",
  "crouching",
  "target lock",
  "item crafting",
  "gesturing",
];
