export const LABEL = "People";
export const OPTIONS = [
  "Tarnished",
  "warrior",
  "swordfighter",
  "knight",
  "samurai",
  "sorcerer",
  "cleric",
  "sage",
  "merchant",
  "teacher",
  "master",
  "friend",
  "lover",
  "old dear",
  "old codger",
  "angel",
  "fat coinpurse",
  "pauper",
  "good sort",
  "wicked sort",
  "plump sort",
  "skinny sort",
  "lovable sort",
  "pathetic sort",
  "strange sort",
  "nimble sort",
  "laggardly sort",
  "invisible sort",
  "unfathomable sort",
  "giant sort",
  "sinner",
  "thief",
  "liar",
  "dastard",
  "traitor",
  "pair",
  "trio",
  "noble",
  "aristocrat",
  "hero",
  "champion",
  "monarch",
  "lord",
  "god",
];
