export const LABEL = "Situations";
export const OPTIONS = [
  "morning",
  "noon",
  "evening",
  "night",
  "clear sky",
  "overcast",
  "rain",
  "storm",
  "mist",
  "snow",
  "patrolling",
  "procession",
  "crowd",
  "surprise attack",
  "ambush",
  "pincer attack",
  "beating to a pulp",
  "battle",
  "reinforcements",
  "ritual",
  "explosion",
  "high spot",
  "defensible spot",
  "climbable spot",
  "bright spot",
  "dark spot",
  "open area",
  "cramped area",
  "hiding place",
  "sniping spot",
  "recon spot",
  "safety",
  "danger",
  "gorgeous view",
  "detour",
  "hidden path",
  "secret passage",
  "shortcut",
  "dead end",
  "looking away",
  "unnoticed",
  "out of stamina",
];
